// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"

	"github.com/google/uuid"
)

// This table is used to store master items
type Item struct {
	ID        uuid.UUID
	TypeID    sql.NullInt32
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

// This table is used to store item types
type ItemType struct {
	ID          int32
	Name        string
	Description sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type SchemaMigration struct {
	Version int64
	Dirty   bool
}

// This table stores user information
type User struct {
	ID        uuid.UUID
	Name      string
	Email     string
	Password  string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
