// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// This table is used to store master items
type Item struct {
	ID        pgtype.UUID
	TypeID    *int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

// This table is used to store item types
type ItemType struct {
	ID          int32
	Name        string
	Description *string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type SchemaMigration struct {
	Version int64
	Dirty   bool
}

// This table stores user information
type User struct {
	ID        pgtype.UUID
	Name      string
	Email     string
	Password  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
