// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package builder

import (
	"database/sql"
	"github.com/SoraDaibu/go-clean-starter/config"
	user3 "github.com/SoraDaibu/go-clean-starter/internal/http/handler/user"
	"github.com/SoraDaibu/go-clean-starter/internal/repository"
	item2 "github.com/SoraDaibu/go-clean-starter/internal/repository/item"
	user2 "github.com/SoraDaibu/go-clean-starter/internal/repository/user"
	"github.com/SoraDaibu/go-clean-starter/internal/service/user"
	"github.com/SoraDaibu/go-clean-starter/internal/task/item"
	"github.com/google/wire"
)

import (
	_ "github.com/lib/pq"
)

// Injectors from wire.go:

// InitializeUserUsecase creates a new UserUsecase instance
func InitializeUserUsecase(d *Dependency) user.UserUsecase {
	db := provideDBFromDependency(d)
	userRepository := user2.NewUserRepository(db)
	userUsecase := user.NewUserUsecase(userRepository)
	return userUsecase
}

// InitializeUserHandler creates a new UserHandler instance
func InitializeUserHandler(d *Dependency) *user3.UserHandler {
	db := provideDBFromDependency(d)
	userRepository := user2.NewUserRepository(db)
	userUsecase := user.NewUserUsecase(userRepository)
	userHandler := user3.NewUserHandler(userUsecase)
	return userHandler
}

// InitializeItemTaskUsecase creates a new ItemTaskUsecase instance
func InitializeItemTaskUsecase(d *Dependency) item.ItemTaskUsecase {
	db := provideDBFromDependency(d)
	transaction := repository.NewTransaction(db)
	itemRepository := item2.NewItemRepository(db)
	itemTaskUsecase := item.NewItemTaskUsecase(transaction, itemRepository)
	return itemTaskUsecase
}

// wire.go:

var (
	// UserUsecaseSet provides all dependencies for UserUsecase
	UserUsecaseSet = wire.NewSet(
		provideDBFromDependency, user2.NewUserRepository, user.NewUserUsecase,
	)

	// ItemTaskUsecaseSet provides all dependencies for ItemTaskUsecase
	ItemTaskUsecaseSet = wire.NewSet(
		provideDBFromDependency, repository.NewTransaction, item2.NewItemRepository, item.NewItemTaskUsecase,
	)
)

// InitializeDependency creates a new Dependency instance with all required dependencies
func InitializeDependency(cfg *config.Config) (*Dependency, error) {
	return Resolve(cfg, NewDependencyNeedsAllTrue())
}

func provideDBFromDependency(d *Dependency) *sql.DB {
	return d.DB
}
